name: build-all
run-name: Build all
on: [push]
jobs:
  build-ubuntu:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: ./setup_robolib.sh && TERM=xterm make
