name: build-all
run-name: Build all
on: [push]
jobs:

  build-ubuntu:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: ./setup_robolib.sh
      #- run: sed -i robolib/make/Makefile -e "s/ -Wall / -Wall -Werror /g"
      - run: TERM=xterm make

  clang-format-changed-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: sudo apt install clang-format
      - run: git clang-format origin/master
      - run: if [ "$(git status --porcelain)" != "" ]; then git diff; return -1; fi
